import { RepoData } from "../models/repo-data"
import { UserDetails } from "../models/user-details"

export const userDetails:UserDetails = {
    "login": "freeCodeCamp",
    "id": 9892522,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjk4OTI1MjI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/9892522?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/freeCodeCamp",
    "html_url": "https://github.com/freeCodeCamp",
    "followers_url": "https://api.github.com/users/freeCodeCamp/followers",
    "following_url": "https://api.github.com/users/freeCodeCamp/following{/other_user}",
    "gists_url": "https://api.github.com/users/freeCodeCamp/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/freeCodeCamp/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/freeCodeCamp/subscriptions",
    "organizations_url": "https://api.github.com/users/freeCodeCamp/orgs",
    "repos_url": "https://api.github.com/users/freeCodeCamp/repos",
    "events_url": "https://api.github.com/users/freeCodeCamp/events{/privacy}",
    "received_events_url": "https://api.github.com/users/freeCodeCamp/received_events",
    "type": "Organization",
    "site_admin": false,
    "name": "freeCodeCamp.org",
    "company": null,
    "blog": "https://freecodecamp.org",
    "location": "Just here on Earth... for now",
    "email": null,
    "hireable": null,
    "bio": "Learn to code for free with millions of other people around the world",
    "twitter_username": "freeCodeCamp",
    "public_repos": 209,
    "public_gists": 5,
    "followers": 9922,
    "following": 0,
    "created_at": "2014-11-22T00:12:57Z",
    "updated_at": "2023-03-04T12:19:53Z"
}

export const repoDetails :RepoData = {
    id: 76098639,
    node_id: "MDEwOlJlcG9zaXRvcnk3NjA5ODYzOQ==",
    name: "about",
    full_name: "freeCodeCamp/about",
    private: false,
    owner: {
      login: "freeCodeCamp",
      id: 9892522,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjk4OTI1MjI=",
      avatar_url: "https://avatars.githubusercontent.com/u/9892522?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/freeCodeCamp",
      html_url: "https://github.com/freeCodeCamp",
      followers_url: "https://api.github.com/users/freeCodeCamp/followers",
      following_url: "https://api.github.com/users/freeCodeCamp/following{/other_user}",
      gists_url: "https://api.github.com/users/freeCodeCamp/gists{/gist_id}",
      starred_url: "https://api.github.com/users/freeCodeCamp/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/freeCodeCamp/subscriptions",
      organizations_url: "https://api.github.com/users/freeCodeCamp/orgs",
      repos_url: "https://api.github.com/users/freeCodeCamp/repos",
      events_url: "https://api.github.com/users/freeCodeCamp/events{/privacy}",
      received_events_url: "https://api.github.com/users/freeCodeCamp/received_events",
      type: "Organization",
      site_admin: false
    },
    html_url: "https://github.com/freeCodeCamp/about",
    description: "freeCodeCamp's static about page",
    fork: false,
    url: "https://api.github.com/repos/freeCodeCamp/about",
    forks_url: "https://api.github.com/repos/freeCodeCamp/about/forks",
    keys_url: "https://api.github.com/repos/freeCodeCamp/about/keys{/key_id}",
    collaborators_url: "https://api.github.com/repos/freeCodeCamp/about/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/freeCodeCamp/about/teams",
    hooks_url: "https://api.github.com/repos/freeCodeCamp/about/hooks",
    issue_events_url: "https://api.github.com/repos/freeCodeCamp/about/issues/events{/number}",
    events_url: "https://api.github.com/repos/freeCodeCamp/about/events",
    assignees_url: "https://api.github.com/repos/freeCodeCamp/about/assignees{/user}",
    branches_url: "https://api.github.com/repos/freeCodeCamp/about/branches{/branch}",
    tags_url: "https://api.github.com/repos/freeCodeCamp/about/tags",
    blobs_url: "https://api.github.com/repos/freeCodeCamp/about/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/freeCodeCamp/about/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/freeCodeCamp/about/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/freeCodeCamp/about/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/freeCodeCamp/about/statuses/{sha}",
    languages_url: "https://api.github.com/repos/freeCodeCamp/about/languages",
    stargazers_url: "https://api.github.com/repos/freeCodeCamp/about/stargazers",
    contributors_url: "https://api.github.com/repos/freeCodeCamp/about/contributors",
    subscribers_url: "https://api.github.com/repos/freeCodeCamp/about/subscribers",
    subscription_url: "https://api.github.com/repos/freeCodeCamp/about/subscription",
    commits_url: "https://api.github.com/repos/freeCodeCamp/about/commits{/sha}",
    git_commits_url: "https://api.github.com/repos/freeCodeCamp/about/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/freeCodeCamp/about/comments{/number}",
    issue_comment_url: "https://api.github.com/repos/freeCodeCamp/about/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/freeCodeCamp/about/contents/{+path}",
    compare_url: "https://api.github.com/repos/freeCodeCamp/about/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/freeCodeCamp/about/merges",
    archive_url: "https://api.github.com/repos/freeCodeCamp/about/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/freeCodeCamp/about/downloads",
    issues_url: "https://api.github.com/repos/freeCodeCamp/about/issues{/number}",
    pulls_url: "https://api.github.com/repos/freeCodeCamp/about/pulls{/number}",
    milestones_url: "https://api.github.com/repos/freeCodeCamp/about/milestones{/number}",
    notifications_url: "https://api.github.com/repos/freeCodeCamp/about/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/freeCodeCamp/about/labels{/name}",
    releases_url: "https://api.github.com/repos/freeCodeCamp/about/releases{/id}",
    deployments_url: "https://api.github.com/repos/freeCodeCamp/about/deployments",
    created_at: "2016-12-10T07:49:43Z",
    updated_at: "2020-08-12T17:11:35Z",
    pushed_at: "2019-08-18T21:45:26Z",
    git_url: "git://github.com/freeCodeCamp/about.git",
    ssh_url: "git@github.com:freeCodeCamp/about.git",
    clone_url: "https://github.com/freeCodeCamp/about.git",
    svn_url: "https://github.com/freeCodeCamp/about",
    homepage: "",
    size: 246,
    stargazers_count: 4,
    watchers_count: 4,
    language: "CSS",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 9,
    mirror_url: null,
    archived: true,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: "bsd-3-clause",
      name: 'BSD 3-Clause \"New\" or \"Revised\" License',
      spdx_id: "BSD-3-Clause",
      url: "https://api.github.com/licenses/bsd-3-clause",
      node_id: "MDc6TGljZW5zZTU="
    },
    allow_forking: true,
    is_template: false,
    topics: ['node','angular'],
    visibility: "public",
    forks: 9,
    open_issues: 0,
    watchers: 4,
    default_branch: "master"
  }